# Generated by Django 3.1.4 on 2020-12-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20201205_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='registration_token',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
