# Generated by Django 3.1.4 on 2020-12-08 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20201207_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ta',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ta_account', serialize=False, to='dashboard.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_ta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='tas',
            field=models.ManyToManyField(blank=True, to='dashboard.Ta'),
        ),
    ]
