# Generated by Django 3.1.4 on 2020-12-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_student_registration_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='hard',
            field=models.BooleanField(default=False),
        ),
    ]
