# Generated by Django 3.1.4 on 2020-12-06 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_deadline_hard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.course'),
        ),
    ]
